### ISSUE TITLE
I can't fully build the software on Windows

### ISSUE THREAD

**Issue by xDevi69** [Tinob/Ishiiruka#133]
I've installed Visual Studio 2017 Community edition (Free) and all the dependencies in the readme (Git and Windows 10 SDK 10.0.15063.0).

When I try to build the program my building window show this: https://pastebin.com/J7re94UU
I can't build 5 out of 36.

What am I doing wrong? I have to install something else? It's the first time I build a program.

**Comment by billywade** [comment]
Did you install DX9? It looks like that's what the compile is hanging on.

https://www.microsoft.com/en-us/download/details.aspx?id=34429

**Comment by xDevi69** [comment]
DX9 is installed. I checked now.
 Sorry If I seem rude but a normal user like me installed Visual studio plus all the dependencies ecc... 
Why the developer doesn't provide the program installer in the assets of the project? I'm just a user that wants to try the program, I don't want to modify it.

**Comment by billywade** [comment]
Try using the solution given here: https://stackoverflow.com/questions/24381974/cannot-open-include-file-d3dx9-h-no-such-file-or-directory

I figure that Tino doesn't have releases because this is a hobby project built on top of his _other_ hobby project, and it's just more hassle than he wants to deal with. That said, once you have it built you can always send him an email or something or open a pull request to add in the release you build.

**Comment by Tinob** [comment]
@xDevi69: if you are interested only  using it and not modify is the best that you just download the latest realeses from here:
https://goo.gl/31cRcc
https://goo.gl/YzHNa5
https://goo.gl/9JiSqB

**Comment by xDevi69** [comment]
Thank you
